### ISSUE TITLE
allow to filter messages

### ISSUE THREAD

**Issue by muzzol** [smjltd/SMStoTelegram#4]
this is a feature request for filtering.

it would be nice if you could filter by text string or origin number to deliver only certain messages.

this is very common in mail programs and adds a level of security if you redirect sensible information to a group.

**Comment by smjltd** [comment]
https://www.smj.ltd/SMStoTelegram/apks/SMStoTelegram-2020.03.21-22.20.03.apk

**Comment by rizhenkov** [comment]
Samsung devices has a feature to mute some senders. Does it possible to detect such messages and not send notification?

**Comment by smjltd** [comment]
Will see what we can do about it.
